### ISSUE TITLE
need a gap between the name and the header

### ISSUE THREAD

**Issue by varsha117** [varsha117/Personal-website#9]
1. and theres a too much gap between the photo and the header 
![Screenshot (212)](https://user-images.githubusercontent.com/85178156/197476588-1fea6179-31d8-4db0-b4fe-5e6466c57257.png)

**Comment by varsha117** [comment]
![vv](https://user-images.githubusercontent.com/85178156/197476995-5d9d1c88-6fb9-4bee-8b7d-127832ec8e1f.png)
something like this would be good

**Comment by pinnheads** [comment]
You don't want the navbar in the about page?

**Comment by varsha117** [comment]
no ig

**Comment by pinnheads** [comment]
How is a user supposed to go back to the main page then?

**Comment by pinnheads** [comment]
IMO it won't be a good feature from an end user perspective.

**Comment by pinnheads** [comment]
![image](https://user-images.githubusercontent.com/49411434/197479118-2aeb7334-ad4a-4410-92ec-e52c1e6d1b16.png)
![image](https://user-images.githubusercontent.com/49411434/197479281-21af7385-319d-4f8f-adaf-7499985098d4.png)

This is how it would look. Doing this will have the following impacts
1. As I said a user will only be able to go back by clicking on the back button on the browser and your resume and portfolio traffic will be reduced significantly. Hence reducing your chances of getting hired.
2. Even on your [inspiration website](https://juliafernandez.design/about) she doesn't hide the navbar that has all the portfolio and resumes links.

So in my opinion we should not remove the navbar the space looks fine to me but I'll leave it up to you
